export { About } from './About/About.jsx';
export { Contact } from './Contact/Contact.jsx';
export { Education } from './Education/Education.jsx';
export { Experience } from './Experience/Experience.jsx';
export { Footer } from './Footer/Footer.jsx';
export { Home } from './Home/Home.jsx';
export { Nav } from './Nav/Nav.jsx';
export { Portfolio } from './Portfolio/Portfolio.jsx';
export { Skills } from './Skills/Skills.jsx';
